version: '3.8'

services:
  web:
    build: ./my_site
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./my_site/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
