version: '3.3'
services:
  web:
    build:
      context: ./my_site
      dockerfile: Dockerfile.prod
    container_name: MyDjangoSite_web
    command: gunicorn my_resume.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod.ansible
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    container_name: MyDjangoSite_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db.ansible
  nginx:
    build: ./nginx
    container_name: MyDjangoSite_nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
